### ISSUE TITLE
Panic during directory scan

### ISSUE THREAD

**Issue by luhring** [anchore/grype#353]
**What happened**: I ran `grype .` in my local "syft" repo directory, and grype exited with a panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18ea1a1]

goroutine 67 [running]:
github.com/anchore/grype/grype/matcher/apk.(*Matcher).cpeMatchesWithoutSecDbFixes(0x2329a98, 0x1d8a4b0, 0xc013c646e0, 0x0, 0xc0239fb0e0, 0x24, 0xc023589c02, 0xa, 0xc023589c12, 0x8, ...)
        /Users/runner/work/grype/grype/grype/matcher/apk/matcher.go:60 +0x101
github.com/anchore/grype/grype/matcher/apk.(*Matcher).Match(0x2329a98, 0x1d8a4b0, 0xc013c646e0, 0x0, 0xc0239fb0e0, 0x24, 0xc023589c02, 0xa, 0xc023589c12, 0x8, ...)
        /Users/runner/work/grype/grype/grype/matcher/apk/matcher.go:35 +0x199
github.com/anchore/grype/grype/matcher.(*controller).findMatches(0x22f5668, 0x1d8a4b0, 0xc013c646e0, 0x0, 0xc025280000, 0x29d, 0x29d, 0xc000183400)
        /Users/runner/work/grype/grype/grype/matcher/controller.go:95 +0x3b5
github.com/anchore/grype/grype/matcher.FindMatches(...)
        /Users/runner/work/grype/grype/grype/matcher/controller.go:113
github.com/anchore/grype/grype.FindVulnerabilitiesForPackage(...)
        /Users/runner/work/grype/grype/grype/lib.go:28
github.com/anchore/grype/cmd.startWorker.func1(0xc0007d4540, 0x7ffeefbff6e6, 0x1, 0x0)
        /Users/runner/work/grype/grype/cmd/root.go:231 +0x385
created by github.com/anchore/grype/cmd.startWorker
        /Users/runner/work/grype/grype/cmd/root.go:170 +0x76
```

**What you expected to happen**: A successful execution that shows vulnerability matches for my "syft" directory.

**How to reproduce it (as minimally and precisely as possible)**: Still working on this. Thus far, I've only seen it for _directory_ scans, and not all directories trigger the panic.

**Environment**:
- Output of `grype version`:

```
Application:          grype
Version:              0.13.0
BuildDate:            2021-06-02T01:57:12Z
GitCommit:            3d21b8397d65770d292184b09a4f676bce6f3ec8
GitTreeState:         clean
Platform:             darwin/amd64
GoVersion:            go1.16.4
Compiler:             gc
Supported DB Schema:  3
```

- OS (e.g: `cat /etc/os-release` or similar): macOS 11.4

**Comment by luhring** [comment]
This happens because Alpine packages have been discovered, and thus the Alpine matcher gets invoked. This matcher looks at multiple sources for vulnerabilities, and for a subset of these sources, a distro is required to produce matches.
