### ISSUE TITLE
Panic if metadata.json is missing from the database cache directory

### ISSUE THREAD

**Issue by luhring** [anchore/grype#471]
**What happened**:

I was testing out what an "air-gapped workflow" might entail, in particular by copying over just `vulnerability.db` (and not `metadata.json`) to Grype's database cache directory. And when I ran Grype with the `GRYPE_DB_AUTO_UPDATE` environment variable set to `false`, it panicked. 😱 

**What you expected to happen**:

At minimum, I expected an error message and no panic. But perhaps Grype could've also fully recovered in that situation somehow (not sure if this makes sense given the "air-gapped" presumption 🤔 ).

**How to reproduce it (as minimally and precisely as possible)**:

1. Rename or remove the file `~/Library/Caches/grype/db/3/metadata.json`.
2. Run a vulnerability scan with the `GRYPE_DB_AUTO_UPDATE` environment variable set to `false`.
3. Observe the panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x191bda3]

goroutine 28 [running]:
github.com/anchore/grype/grype/matcher/common.FindMatchesByPackageDistro(0x0, 0x0, 0xc013c26c40, 0xc0007b00c0, 0x24, 0xc000612900, 0x7, 0xc000612910, 0xc, 0xc0139587e0, ...)
	/Users/runner/work/grype/grype/grype/matcher/common/distro_matchers.go:28 +0x203
github.com/anchore/grype/grype/matcher/dpkg.(*Matcher).Match(0x247bc88, 0x0, 0x0, 0xc013c26c40, 0xc0007b00c0, 0x24, 0xc000612900, 0x7, 0xc000612910, 0xc, ...)
	/Users/runner/work/grype/grype/grype/matcher/dpkg/matcher.go:36 +0x28f
github.com/anchore/grype/grype/matcher.(*controller).findMatches(0x2446a80, 0x0, 0x0, 0xc013c26c40, 0xc0004be800, 0x5c, 0x5c, 0xc0002822c0)
	/Users/runner/work/grype/grype/grype/matcher/controller.go:97 +0x3b5
github.com/anchore/grype/grype/matcher.FindMatches(...)
	/Users/runner/work/grype/grype/grype/matcher/controller.go:115
github.com/anchore/grype/grype.FindVulnerabilitiesForPackage(...)
	/Users/runner/work/grype/grype/grype/lib.go:28
github.com/anchore/grype/cmd.startWorker.func1(0xc000042900, 0x7ffeefbff6a6, 0x1f, 0x0)
	/Users/runner/work/grype/grype/cmd/root.go:233 +0x385
created by github.com/anchore/grype/cmd.startWorker
	/Users/runner/work/grype/grype/cmd/root.go:172 +0x76
```

**Anything else we need to know?**: I think for "normal usage" this failure mode might seem contrived. But as we help users with airgapped or Internet-restricted setups, I think this is a rough edge that ought to be smoothed out.

**Environment**:
- Output of `grype version`:

```
Application:          grype
Version:              0.23.0
Syft Version:         v0.24.1
BuildDate:            2021-10-11T12:51:42Z
GitCommit:            2dd41311cb250a621db615f5f7085edda88e4bb1
GitTreeState:         clean
Platform:             darwin/amd64
GoVersion:            go1.16.8
Compiler:             gc
Supported DB Schema:  3
```

- OS (e.g: `cat /etc/os-release` or similar): macOS 11.6 (20G165)

**Comment by luhring** [comment]
This looks like it's been resolved in the current release (and possibly prior releases, too). I'll close this.
