### ISSUE TITLE
Panic: runtime error - when utilizing the vulnerability scanner on an cyclonedx sbom file input

### ISSUE THREAD

**Issue by kbolander** [anchore/grype#669]
**What happened**:
I received a `panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc80ac1]` error when attempting to run grype on a valid cyclonedx SBOM. I've attached the sample SBOM I was attempting to scan (note, I had to save this as a .txt file in order to upload, so you'll need to change the extension to .json to test it fully). 

**What you expected to happen**:
Expected the scan to run without any errors. 

**How to reproduce it (as minimally and precisely as possible)**:
[sbom.cyclonedx.txt](https://github.com/anchore/grype/files/8257054/sbom.cyclonedx.txt)
Use the above file and run `grype sbom:./sbom.cyclonedx.json` 
As stated before, just make sure you change the file to a .json before running. 

**Anything else we need to know?**:
Here's the full stack of the error:
```
grype sbom:./sbom.cyclonedx.json
 ⠋ Vulnerability DB        [checking for update]panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc80ac1]

goroutine 83 [running]:
github.com/anchore/syft/internal/formats/common/cyclonedxhelpers.decodeComponent(0xc000780000)
        /Users/runner/go/pkg/mod/github.com/anchore/syft@v0.41.4/internal/formats/common/cyclonedxhelpers/component.go:50 +0xa1
github.com/anchore/syft/internal/formats/common/cyclonedxhelpers.collectPackages(0xc000780000, 0xc000580ea0, 0x0)
        /Users/runner/go/pkg/mod/github.com/anchore/syft@v0.41.4/internal/formats/common/cyclonedxhelpers/decoder.go:87 +0x105
github.com/anchore/syft/internal/formats/common/cyclonedxhelpers.collectBomPackages(0xc000228fd0, 0x0, 0xc)
        /Users/runner/go/pkg/mod/github.com/anchore/syft@v0.41.4/internal/formats/common/cyclonedxhelpers/decoder.go:77 +0x79
github.com/anchore/syft/internal/formats/common/cyclonedxhelpers.toSyftModel(0xc000228fd0)
        /Users/runner/go/pkg/mod/github.com/anchore/syft@v0.41.4/internal/formats/common/cyclonedxhelpers/decoder.go:63 +0x305
github.com/anchore/syft/internal/formats/common/cyclonedxhelpers.GetDecoder.func1({0x162fe20, 0xc000edfbc0})
        /Users/runner/go/pkg/mod/github.com/anchore/syft@v0.41.4/internal/formats/common/cyclonedxhelpers/decoder.go:39 +0xe6
github.com/anchore/syft/syft/sbom.format.Decode(...)
        /Users/runner/go/pkg/mod/github.com/anchore/syft@v0.41.4/syft/sbom/format.go:69
github.com/anchore/syft/syft.Decode({0x1634140, 0xc000020050})
        /Users/runner/go/pkg/mod/github.com/anchore/syft@v0.41.4/syft/encode_decode.go:34 +0x10f
github.com/anchore/grype/grype/pkg.syftSBOMProvider({0x7ffdf99780b9, 0xc0000b5698}, {0xc000022540, {0x2095b08, 0x0, 0x0}, {{0x1, 0x0, {0x1335650, 0x8}}}, ...})
        /Users/runner/work/grype/grype/grype/pkg/syft_sbom_provider.go:23 +0x33
github.com/anchore/grype/grype/pkg.Provide({0x7ffdf99780b9, 0x1a}, {0xc000022540, {0x2095b08, 0x0, 0x0}, {{0x1, 0x0, {0x1335650, 0x8}}}, ...})
        /Users/runner/work/grype/grype/grype/pkg/provider.go:16 +0x59
github.com/anchore/grype/cmd.startWorker.func1.2()
        /Users/runner/work/grype/grype/cmd/root.go:292 +0x149
created by github.com/anchore/grype/cmd.startWorker.func1
        /Users/runner/work/grype/grype/cmd/root.go:289 +0x686
```
**Environment**:
- Output of `grype version`: 
```
Application:          grype
Version:              0.34.1
Syft Version:         v0.41.4
BuildDate:            2022-03-15T14:10:38Z
GitCommit:            0b76016235332f66ceac7e266c0278b86d3a23cf
GitDescription:       v0.34.1
Platform:             linux/amd64
GoVersion:            go1.17.7
Compiler:             gc
Supported DB Schema:  3
```
- OS (e.g: `cat /etc/os-release` or similar):
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by kzantow** [comment]
Thanks for reporting this and especially providing a sample SBOM!

**Comment by kzantow** [comment]
Simple solution here: https://github.com/anchore/syft/pull/892 :)
