### ISSUE TITLE
 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nijel** [anchore/grype#702]
**What happened**:

Recently, anchore/scan-action@v3 started to fail on https://github.com/WeblateOrg/docker with:

```
[0030]  WARN cataloger 'java-cataloger' failed to parse entries at location=Location<id=41831 RealPath="/usr/local/lib/python3.10/site-packages/weblate/trans/tests/data/invalid.zip" VirtualPath="/usr/local/lib/python3.10/site-packages/weblate/trans/tests/data/invalid.zip" Layer="sha256:4271cbe04d0fbb62dec12411705efb9787dfd51d10a107d8e3335f549a19d566">: unable to read files from java archive: unable to open zip archive (/tmp/syft-archive-contents-2446333362/archive-invalid.zip): cannot find beginning of zip archive="/tmp/syft-archive-contents-2446333362/archive-invalid.zip" : zip: not a valid zip file from-lib=syft
  
  panic: runtime error: invalid memory address or nil pointer dereference
  [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1018049]
  
  goroutine 1 [running]:
  github.com/anchore/grype/grype/presenter/sarif.(*Presenter).cvssScore(0xc01a698840, {{0x1643fc0, 0xc020065d00}, {0x2095b08, 0x0
  , 0x0}, {0xc01faa0350, 0xd}, {0xc01faa0360, 0x9}, ...})
  	/Users/runner/work/grype/grype/grype/presenter/sarif/presenter.go:258 +0x1e9
  github.com/anchore/grype/grype/presenter/sarif.(*Presenter).securitySeverityValue(_, {{{0x1643fc0, 0xc020065d00}, {0x2095b08, 0x0, 0x0}, {0xc01faa0350, 0xd}, {0xc01faa0360, 0x9}, ...}, ...})
  	/Users/runner/work/grype/grype/grype/presenter/sarif/presenter.go:290 +0xe5
  github.com/anchore/grype/grype/presenter/sarif.(*Presenter).sarifRules(0xc01a698840)
  	/Users/runner/work/grype/grype/grype/presenter/sarif/presenter.go:116 +0x725
  github.com/anchore/grype/grype/presenter/sarif.(*Presenter).toSarifReport(0x12d55a0)
  	/Users/runner/work/grype/grype/grype/presenter/sarif/presenter.go:65 +0x218
  github.com/anchore/grype/grype/presenter/sarif.(*Presenter).Present(0x466a4e, {0x16341a0, 0xc00000e018})
  	/Users/runner/work/grype/grype/grype/presenter/sarif/presenter.go:38 +0x25
  github.com/anchore/grype/internal/ui.handleVulnerabilityScanningFinished({{0x136a53c, 0x25}, {0x0, 0x0}, {0x12d55a0, 0xc01a698840}, {0x0, 0x0}}, {0x16341a0, 0xc00000e018})
  	/Users/runner/work/grype/grype/internal/ui/common_event_handlers.go:19 +0x2a7
  github.com/anchore/grype/internal/ui.loggerUI.Handle({0xc0001fc500, {0x16341a0, 0xc00000e018}}, {{0x136a53c, 0x25}, {0x0, 0x0}, {0x12d55a0, 0xc01a698840}, {0x0, ...}})
  	/Users/runner/work/grype/grype/internal/ui/logger_ui.go:35 +0xd1
  github.com/anchore/grype/cmd.eventLoop(0xc000554a20, 0xc00024f2c0, 0xc0003cadc0, 0xe, {0xc0001fc4f0, 0x1, 0x1})
  	/Users/runner/work/grype/grype/cmd/event_loop.go:55 +0x368
  github.com/anchore/grype/cmd.rootExec(0xd, {0xc00025a000, 0xc00053fdb0, 0x5e0d65})
  	/Users/runner/work/grype/grype/cmd/root.go:219 +0x1c8
  github.com/anchore/grype/cmd.glob..func2(0x2039f40, {0xc00025a000, 0x1, 0x5})
  	/Users/runner/work/grype/grype/cmd/root.go:79 +0x190
  github.com/spf13/cobra.(*Command).execute(0x2039f40, {0xc00003a1f0, 0x5, 0x5})
  	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
  github.com/spf13/cobra.(*Command).ExecuteC(0x2039f40)
  	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
  github.com/spf13/cobra.(*Command).Execute(...)
  	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
  github.com/anchore/grype/cmd.Execute()
  	/Users/runner/work/grype/grype/cmd/cmd.go:41 +0x25
  main.main()
  	/Users/runner/work/grype/grype/main.go:8 +0x17
```

I'm not aware of any related change on our side, so it is most likely something in the action or grype. The full log can be found here:

https://github.com/WeblateOrg/docker/runs/5765205172?check_suite_focus=true

**What you expected to happen**:

No panic :-)

**How to reproduce it (as minimally and precisely as possible)**:

Sorry, I have no clue what is causing the crash.

**Anything else we need to know?**:

**Environment**:
- GitHub Action reports v0.34.1

**Comment by xendk** [comment]
We've been seeing this too.

**Comment by kzantow** [comment]
Ah, looks like this was already fixed in Syft [v0.34.3](https://github.com/anchore/grype/releases/tag/v0.34.3) we just needed to get the scan-action updated. I published a new version: https://github.com/anchore/scan-action/releases/tag/v3.2.2

I was able to verify this same error using `v0.34.1` and that it is fixed using:
```
grype -o sarif --fail-on high weblate/weblate:latest
```

**Comment by PriceChild** [comment]
@kzantow Thanks, my case is working again now.

**Comment by kzantow** [comment]
@nijel if you have a chance, would you be able to verify this works for you now?

**Comment by xendk** [comment]
Fixed it here too.

**Comment by nijel** [comment]
Sorry for not responding, I was busy with other stuff. The scan works fine with 0.34.4, thanks for pushing the fix!
