### ISSUE TITLE
Panic while running scan on directory

### ISSUE THREAD

**Issue by umeshkumhar** [anchore/grype#715]
**What happened**:
grype throws panic while running scan on mounted ubuntu.qcow2 image.

```bash
> sudo grype dir:/umes                                                                 7m 33s 12:55:42 PM
 ✔ Vulnerability DB        [no update available]
 ⠴ Indexing /umes          [file: /umes/var/log/lastlog]panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xbad731]

goroutine 70 [running]:
github.com/anchore/syft/syft/source.(*directoryResolver).indexPath(0xc000146000, {0xc000f1b510, 0xf}, {0x0, 0x0}, {0x16ac400, 0xc003414bd0})
	/Users/runner/go/pkg/mod/github.com/anchore/syft@v0.42.4/syft/source/directory_resolver.go:138 +0x111
github.com/anchore/syft/syft/source.(*directoryResolver).indexTree.func1({0xc000f1b510?, 0xf?}, {0x0?, 0x0?}, {0x16ac400?, 0xc003414bd0?})
	/Users/runner/go/pkg/mod/github.com/anchore/syft@v0.42.4/syft/source/directory_resolver.go:120 +0x85
path/filepath.Walk({0xc000f1b510, 0xf}, 0xc000e1d730)
	/Users/runner/hostedtoolcache/go/1.18.0/x64/src/path/filepath/path.go:503 +0x50
github.com/anchore/syft/syft/source.(*directoryResolver).indexTree(0xc000146000, {0xc000f1b510, 0xf}, 0xc000212090)
	/Users/runner/go/pkg/mod/github.com/anchore/syft@v0.42.4/syft/source/directory_resolver.go:116 +0x27d
github.com/anchore/syft/syft/source.indexAllRoots({0xc00025802b, 0x5}, 0xc000e1da08)
	/Users/runner/go/pkg/mod/github.com/anchore/syft@v0.42.4/syft/source/directory_resolver.go:550 +0x1be
github.com/anchore/syft/syft/source.newDirectoryResolver({0x7ffccbd468aa, 0x5}, {0x0, 0x0, 0x0?})
	/Users/runner/go/pkg/mod/github.com/anchore/syft@v0.42.4/syft/source/directory_resolver.go:88 +0x43b
github.com/anchore/syft/syft/source.(*Source).FileResolver(0xc000172000, {0x137be72?, 0x0?})
	/Users/runner/go/pkg/mod/github.com/anchore/syft@v0.42.4/syft/source/source.go:317 +0x3b3
github.com/anchore/syft/syft.CatalogPackages(0xc000172000, {{0x9?, 0x0?, {0x137be72?, 0xf?}}})
	/Users/runner/go/pkg/mod/github.com/anchore/syft@v0.42.4/syft/lib.go:38 +0x53
github.com/anchore/grype/grype/pkg.syftProvider({0x7ffccbd468a6?, 0xc000db4180?}, {0xc000db4180, {0x2052850, 0x0, 0x0}, {{0x1, 0x0, {0x137be72, 0x8}}}, ...})
	/Users/runner/work/grype/grype/grype/pkg/syft_provider.go:24 +0x148
github.com/anchore/grype/grype/pkg.Provide({0x7ffccbd468a6, 0x9}, {0xc000db4180, {0x2052850, 0x0, 0x0}, {{0x1, 0x0, {0x137be72, 0x8}}}, ...})
	/Users/runner/work/grype/grype/grype/pkg/provider.go:27 +0x18b
github.com/anchore/grype/cmd.startWorker.func1.2()
	/Users/runner/work/grype/grype/cmd/root.go:293 +0x325
created by github.com/anchore/grype/cmd.startWorker.func1
	/Users/runner/work/grype/grype/cmd/root.go:290 +0x67d
```

**What you expected to happen**:

This should run with a result summary of issues in a given path.

**How to reproduce it (as minimally and precisely as possible)**:

1. Mount ubuntu.qcow2 image on host path `/umes`
`guestmount -a ubuntu-14.04-server-amd64.qcow2 -i --ro /umes` 
2. Download latest grype (0.34.7) and run scan
3. Run scan `sudo grype /umes`

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`: 
```bash
Application:          grype
Version:              0.34.7
Syft Version:         v0.42.4
BuildDate:            2022-03-24T19:36:25Z
GitCommit:            44e676488efe4ab4fd63438bbce539777a2b8922
GitDescription:       v0.34.7
Platform:             linux/amd64
GoVersion:            go1.18
Compiler:             gc
Supported DB Schema:  3

```
- OS (e.g: `cat /etc/os-release` or similar):

**Comment by luhring** [comment]
I **_think_** this is the same root issue as https://github.com/anchore/syft/issues/872 — in which case the fix here is to update Grype to the latest Syft.

**Comment by luhring** [comment]
Hi @umeshkumhar — we just released a new update to Grype. I believe this should be fixed, but would you be able to try again and let us know what you see?
